// themes/react/src/components/SearchResults.tsx
import { useRef, useEffect } from 'react'
import type { Article } from '@soul-blog/wc'

interface Props {
  articles: Article[]
  catNames: Record<string, string>
  onResultSelect?: (id: string, cat: string) => void
}

export default function SearchResults({ articles, catNames, onResultSelect }: Props) {
  const ref = useRef<HTMLElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    ;(el as any).articles = articles
    ;(el as any).catNames = catNames
  }, [articles, catNames])

  useEffect(() => {
    const el = ref.current
    if (!el || !onResultSelect) return
    const handler = (e: Event) => {
      const d = (e as CustomEvent).detail
      onResultSelect(d.id, d.cat)
    }
    el.addEventListener('result-select', handler)
    return () => el.removeEventListener('result-select', handler)
  }, [onResultSelect])

  return <search-results ref={ref}></search-results>
}

// themes/vue/src/components/SearchResults.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { Article } from '@soul-blog/wc'

const props = defineProps<{
  articles: Article[]
  catNames: Record<string, string>
}>()

const emit = defineEmits<{
  resultSelect: [id: string, cat: string]
}>()

const wcRef = ref<HTMLElement>()

function setData() {
  const el = wcRef.value
  if (!el) return
  ;(el as any).articles = props.articles
  ;(el as any).catNames = props.catNames
}

onMounted(setData)

watch(() => props.articles, (val) => {
  if (wcRef.value) (wcRef.value as any).articles = val
})

watch(() => props.catNames, (val) => {
  if (wcRef.value) (wcRef.value as any).catNames = val
})
</script>

<template>
  <search-results
    ref="wcRef"
    v-bind="{ articles, catNames }"
    @result-select="emit('resultSelect', ($event as any).detail.id, ($event as any).detail.cat)"
  ></search-results>
</template>
