// themes/vue/src/components/ArchiveList.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { Article } from '@soul-blog/wc'

const props = withDefaults(defineProps<{
  articles: Article[]
  catNames?: Record<string, string>
}>(), {
  catNames: () => ({})
})

const emit = defineEmits<{
  articleSelect: [id: string]
}>()

const wcRef = ref<HTMLElement>()

function setData() {
  const el = wcRef.value
  if (!el) return
  ;(el as any).articles = props.articles
  ;(el as any).catNames = props.catNames
}

onMounted(setData)

watch(() => props.articles, (val) => {
  if (wcRef.value) (wcRef.value as any).articles = val
})

watch(() => props.catNames, (val) => {
  if (wcRef.value) (wcRef.value as any).catNames = val
})
</script>

<template>
  <archive-list
    ref="wcRef"
    :articles.prop="articles"
    :cat-names.prop="catNames"
    @article-select="emit('articleSelect', ($event as any).detail.id)"
  ></archive-list>
</template>

// themes/react/src/components/ArchiveList.tsx
import { useRef, useEffect } from 'react'
import type { Article } from '@soul-blog/wc'

interface Props {
  articles: Article[]
  catNames: Record<string, string>
  onArticleSelect?: (id: string) => void
}

export default function ArchiveList({ articles, catNames, onArticleSelect }: Props) {
  const ref = useRef<HTMLElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    ;(el as any).articles = articles
    ;(el as any).catNames = catNames
  }, [articles, catNames])

  useEffect(() => {
    const el = ref.current
    if (!el || !onArticleSelect) return
    const handler = (e: Event) => onArticleSelect((e as CustomEvent).detail.id)
    el.addEventListener('article-select', handler)
    return () => el.removeEventListener('article-select', handler)
  }, [onArticleSelect])

  return <archive-list ref={ref}></archive-list>
}
