// themes/vue/src/components/ArticleList.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { Article } from '@soul-blog/wc'

const props = defineProps<{
  articles: Article[]
  icons: Record<string, string>
  activeCat: string
  activeTag?: string
}>()

const emit = defineEmits<{
  articleSelect: [id: string]
  tagSelect: [tag: string]
}>()

const wcRef = ref<HTMLElement>()

function setData() {
  const el = wcRef.value
  if (!el) return
  el.setAttribute('active-cat', props.activeCat)
  if (props.activeTag) el.setAttribute('active-tag', props.activeTag)
  ;(el as any).articles = props.articles
  ;(el as any).icons = props.icons
}

onMounted(setData)

watch(() => props.activeCat, (val) => {
  wcRef.value?.setAttribute('active-cat', val)
})

watch(() => props.activeTag, (val) => {
  if (wcRef.value) {
    if (val) wcRef.value.setAttribute('active-tag', val)
    else wcRef.value.removeAttribute('active-tag')
  }
})

watch(() => props.articles, (val) => {
  if (wcRef.value) (wcRef.value as any).articles = val
})

watch(() => props.icons, (val) => {
  if (wcRef.value) (wcRef.value as any).icons = val
})
</script>

<template>
  <article-list
    ref="wcRef"
    v-bind="{ articles, icons }"
    :active-cat="activeCat"
    @article-select="emit('articleSelect', ($event as any).detail.id)"
@tag-select="emit('tagSelect', ($event as any).detail.tag)"
  ></article-list>
</template>

// themes/react/src/components/ArticleList.tsx
import { useRef, useEffect } from 'react'
import type { Article } from '@soul-blog/wc'

interface Props {
  articles: Article[]
  icons: Record<string, string>
  activeCat: string
  activeTag?: string
  onArticleSelect?: (id: string) => void
  onTagSelect?: (tag: string) => void
}

export default function ArticleList({ articles, icons, activeCat, activeTag, onArticleSelect, onTagSelect }: Props) {
  const ref = useRef<HTMLElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    ;(el as any).articles = articles
    ;(el as any).icons = icons
  }, [articles, icons])

  useEffect(() => {
    ref.current?.setAttribute('active-cat', activeCat)
  }, [activeCat])

  useEffect(() => {
    const el = ref.current
    if (!el) return
    if (activeTag) el.setAttribute('active-tag', activeTag)
    else el.removeAttribute('active-tag')
  }, [activeTag])

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const articleHandler = (e: Event) => onArticleSelect?.((e as CustomEvent).detail.id)
    const tagHandler = (e: Event) => onTagSelect?.((e as CustomEvent).detail.tag)
    el.addEventListener('article-select', articleHandler)
    el.addEventListener('tag-select', tagHandler)
    return () => {
      el.removeEventListener('article-select', articleHandler)
      el.removeEventListener('tag-select', tagHandler)
    }
  }, [onArticleSelect, onTagSelect])

  return <article-list ref={ref} active-cat="all"></article-list>
}
