// themes/vue/src/components/ArticleViewer.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { Article, GiscusConfig } from '@soul-blog/wc'

const props = defineProps<{
  article: Article | null
  articles: Article[]
  icons: Record<string, string>
  giscus: GiscusConfig
}>()

const emit = defineEmits<{
  articleSelect: [id: string, cat: string]
  tagSelect: [tag: string]
  viewerClose: []
}>()

const wcRef = ref<HTMLElement>()

function openWithFlip(cardEl: HTMLElement | null, siteName: string) {
  if (wcRef.value) {
    (wcRef.value as any).openWithFlip(cardEl, siteName)
  }
}

function closeWithFlip() {
  if (wcRef.value) {
    (wcRef.value as any).closeWithFlip()
  }
}

// 阅读器内标签点击：preventDefault 表示已由 vue-router 接管，
// 组件将不再自行关闭阅读器/改写 location.hash
function onWcTagSelect(value: unknown) {
  const event = value as CustomEvent<{ tag?: string }>
  event.preventDefault()
  if (event.detail?.tag) emit('tagSelect', event.detail.tag)
}

function setData() {
  const el = wcRef.value
  if (!el) return
  ;(el as any).article = props.article
  ;(el as any).articles = props.articles
  ;(el as any).icons = props.icons
  ;(el as any).giscusConfig = props.giscus
}

onMounted(setData)

watch(() => props.article, (val) => {
  if (wcRef.value) (wcRef.value as any).article = val
})

watch(() => props.articles, (val) => {
  if (wcRef.value) (wcRef.value as any).articles = val
})

watch(() => props.icons, (val) => {
  if (wcRef.value) (wcRef.value as any).icons = val
})

watch(() => props.giscus, (val) => {
  if (wcRef.value) (wcRef.value as any).giscusConfig = val
}, { deep: true })

defineExpose({ openWithFlip, closeWithFlip })
</script>

<template>
  <article-viewer
    ref="wcRef"
    v-bind="{ article, articles, icons, giscus }"
    @article-select="emit('articleSelect', ($event as any).detail.id, ($event as any).detail.cat)"
    @tag-select="onWcTagSelect"
    @viewer-close="emit('viewerClose')"
  >
    <span slot="page-views" id="vercount_value_page_pv" aria-label="本文阅读量">—</span>
  </article-viewer>
</template>

// themes/react/src/components/ArticleViewer.tsx
import { useRef, useEffect, forwardRef, useImperativeHandle } from 'react'
import type { Article, GiscusConfig } from '@soul-blog/wc'

interface Props {
  article: Article | null
  articles: Article[]
  icons: Record<string, string>
  giscus: GiscusConfig
  onArticleSelect?: (id: string, cat: string) => void
  onTagSelect?: (tag: string) => void
  onViewerClose?: () => void
}

export interface ArticleViewerHandle {
  openWithFlip: (cardEl: HTMLElement | null, siteName: string) => void
  closeWithFlip: () => void
}

const ArticleViewer = forwardRef<ArticleViewerHandle, Props>(
  function ArticleViewer({ article, articles, icons, giscus, onArticleSelect, onTagSelect, onViewerClose }, ref) {
    const wcRef = useRef<HTMLElement>(null)

    useImperativeHandle(ref, () => ({
      openWithFlip(cardEl: HTMLElement | null, siteName: string) {
        if (wcRef.current) {
          ;(wcRef.current as any).openWithFlip(cardEl, siteName)
        }
      },
      closeWithFlip() {
        if (wcRef.current) {
          ;(wcRef.current as any).closeWithFlip()
        }
      }
    }))

    useEffect(() => {
      const el = wcRef.current
      if (!el) return
      ;(el as any).article = article
    }, [article])

    useEffect(() => {
      const el = wcRef.current
      if (!el) return
      ;(el as any).articles = articles
      ;(el as any).icons = icons
    }, [articles, icons])

    useEffect(() => {
      if (wcRef.current) (wcRef.current as any).giscusConfig = giscus
    }, [giscus])

    useEffect(() => {
      const el = wcRef.current
      if (!el) return
      const handler = (e: Event) => {
        const d = (e as CustomEvent).detail
        onArticleSelect?.(d.id, d.cat)
      }
      const closeHandler = () => onViewerClose?.()
      el.addEventListener('article-select', handler)
      el.addEventListener('viewer-close', closeHandler)
      return () => {
        el.removeEventListener('article-select', handler)
        el.removeEventListener('viewer-close', closeHandler)
      }
    }, [onArticleSelect, onViewerClose])

    // 阅读器内标签点击：preventDefault 表示已由宿主接管路由，
    // 组件将不再自行关闭阅读器/改写 location.hash
    useEffect(() => {
      const el = wcRef.current
      if (!el) return
      const tagHandler = (e: Event) => {
        ;(e as CustomEvent).preventDefault()
        onTagSelect?.(((e as CustomEvent).detail as any)?.tag)
      }
      el.addEventListener('tag-select', tagHandler)
      return () => el.removeEventListener('tag-select', tagHandler)
    }, [onTagSelect])

    return (
      <article-viewer ref={wcRef}>
        <span slot="page-views" id="vercount_value_page_pv" aria-label="本文阅读量">—</span>
      </article-viewer>
    )
  }
)

export default ArticleViewer
